### ISSUE TITLE
Замечания по Clocks

### ISSUE THREAD

**Issue by sergey-shambir** [artyom-yurin/SaAPD#2]
- код можно упростить с помощью [тернарного оператора](http://stackoverflow.com/questions/26448611)

``` cpp
if (position % 5 == 0)
    dot = sf::CircleShape(3);
else
    dot = sf::CircleShape(1);
```
- аналогичное замечание для функции InitDot
- название метода `initHand` нарушает соглашения о кодировании; кроме того, его стоит переименовать в `InitOneHand`, чтобы отличать от соседнего метода
- в настройках среды надо поставить уровень предупреждений 4 и устранить появившиеся предупреждения

**Comment by sergey-shambir** [comment]
Из объявления структуры следует убрать некорректную инициализацию поля:

``` cpp
struct Application
{
    sf::RenderWindow window;
    sf::Vector2f windowCenter = GetWindowCenter(window);
```

**Comment by ortyomka** [comment]
Исправлено
