### ISSUE TITLE
Замечания по коду в поиске пути по лабиринту (Labyrinth)

### ISSUE THREAD

**Issue by sergey-shambir** [artyom-yurin/SaAPD#3]
- код функции ReadLabyrinth достаточно большой, конструкции вида `labyrinth[j + 1][i + 1]` можно вынести в выражение, а общий код вида `(labyrinth[j + 1][i + 1])->x = j + 1; (labyrinth[j + 1][i + 1])->y = i + 1;` вынести в функцию
- назначение функции неясно: `size_t h(size_t y, size_t x, Points & points)`
- названия полей `F` и `G` не соответствуют [соглашениям о кодировании](https://ps-group.github.io/sfml/coding_conventions.html) и не отражают их назначения 
- уверен, код функции FindWay можно сократить хотя бы за счёт лямбда-функций, хотя это и трудно, конечно

**Comment by sergey-shambir** [comment]
Базовая оценка 15 баллов из 10 (т.к. выполнено на продвинутом уровне), 0.7 из-за замечаний по коду, итого сейчас 10,5.

**Comment by ortyomka** [comment]
Исправлено
